name: $pluginName
main: $pluginMain
api-version: "1.17"
version: $version
description: "TNTRun Survival."
author: ContentManager
libraries:
  - io.github.monun:tap:4.1.1
  - io.github.monun:kommand:2.2.0